version: '3.2'
services:
    revive:
        build: .
        image: javi98/revive-adserver
        container_name: revive-adserver
        ports:
         - '8080:80'
        restart: always
        depends_on:
                - db
    db:
        image: mysql:5.7
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: 12345678
          MYSQL_DATABASE: revive
          MYSQL_USER: user
          MYSQL_PASSWORD: 12345678
