version: '3.2'
services:
    revive:
        build: .
        image: dustinhawkins/revive
        container_name: revive
        ports:
         - '8080:80'
        restart: always
        depends_on:
                - db
    db:
        image: mysql:5.7
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: revive
          MYSQL_USER: user
          MYSQL_PASSWORD: password

    phpmyadmin:
        depends_on:
          - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
          - 8088:80
        environment:
          PMA_HOST: db
          MYSQL_ROOT_PASSWORD: password
